name: game2d
description: games in 2d
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  rigidbody2d:
    git: git://github.com/fraog/dart-rigidbody2d.git
